class Roles:
    ADMIN = "admin"
    HR_MANAGER = "hr_manager"
    HR_USER = "hr_user"
    MANAGER = "manager"
    EMPLOYEE = "employee"
    EXPENSE_APPROVER = "expense_approver"
    LEAVE_APPROVER = "leave_approver"
    PROJECT_MANAGER = "project_manager"
    REPORTING_MANAGER = "rm"
    FINANCE = "finance"
    IT_SUPPORT = "it_support"
    LEGAL = "legal"
    RECRUITER = "recruiter"
